# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7307fe63d29f62281b69b3630b3f7f54df8ddb73152184b5898aae6c76d842a5c9410616ba2044c7c9724555c244ffde1ab3657e0405dfd15db41b3c882eb967

test:
  secret_key_base: b7d9bf10ba0fd0df768c94c45976add08dd966aab83b82d3ea741b56ca47440f798ddcab3d330f3aae5982f034e64d35856fd8da90300b29790330cb54d02ea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
